version: "3.8"

services:
  app:
    build: .
    container_name: hackanet_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: always   # Перезапуск контейнера в случае сбоя

  db:
    image: postgres:15
    container_name: hackanet_db
    environment:
      POSTGRES_DB: hackanet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
