version: "3.8"

services:
  app:
    build: .
    container_name: hackanet_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=TaskHub
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: hackanet_db
    environment:
      POSTGRES_DB: hackanet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
